In [1]:
import torch
import numpy as np
import torchvision.transforms as transforms
import PIL

In [6]:
def _data_transforms_cifar10():
  CIFAR_MEAN = [0.49139968, 0.48215827, 0.44653124]
  CIFAR_STD = [0.24703233, 0.24348505, 0.26158768]

  train_transform = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(CIFAR_MEAN, CIFAR_STD),
  ])

  valid_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(CIFAR_MEAN, CIFAR_STD),
    ])
  return train_transform, valid_transform

In [26]:
train_transform, valid_transform = _data_transforms_cifar10()

In [36]:
transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])])(PIL.Image.fromarray(8 * np.ones((32, 32, 3)).astype(np.uint8)))

tensor([[[-0.9373, -0.9373, -0.9373,  ..., -0.9373, -0.9373, -0.9373],
         [-0.9373, -0.9373, -0.9373,  ..., -0.9373, -0.9373, -0.9373],
         [-0.9373, -0.9373, -0.9373,  ..., -0.9373, -0.9373, -0.9373],
         ...,
         [-0.9373, -0.9373, -0.9373,  ..., -0.9373, -0.9373, -0.9373],
         [-0.9373, -0.9373, -0.9373,  ..., -0.9373, -0.9373, -0.9373],
         [-0.9373, -0.9373, -0.9373,  ..., -0.9373, -0.9373, -0.9373]],

        [[-0.9373, -0.9373, -0.9373,  ..., -0.9373, -0.9373, -0.9373],
         [-0.9373, -0.9373, -0.9373,  ..., -0.9373, -0.9373, -0.9373],
         [-0.9373, -0.9373, -0.9373,  ..., -0.9373, -0.9373, -0.9373],
         ...,
         [-0.9373, -0.9373, -0.9373,  ..., -0.9373, -0.9373, -0.9373],
         [-0.9373, -0.9373, -0.9373,  ..., -0.9373, -0.9373, -0.9373],
         [-0.9373, -0.9373, -0.9373,  ..., -0.9373, -0.9373, -0.9373]],

        [[-0.9373, -0.9373, -0.9373,  ..., -0.9373, -0.9373, -0.9373],
         [-0.9373, -0.9373, -0.9373,  ..., -0

In [15]:
import torchvision.datasets as dset
train_data = dset.CIFAR10(root='../data', train=True, download=True)

Files already downloaded and verified


In [20]:
train_transform(train_data[0][0])

tensor([[[-1.9892, -1.9892, -1.9892,  ...,  0.1063,  0.1539,  0.0745],
         [-1.9892, -1.9892, -1.9892,  ..., -0.0684, -0.1001, -0.3541],
         [-1.9892, -1.9892, -1.9892,  ..., -0.0842, -0.2906, -0.5922],
         ...,
         [-1.9892, -1.9892, -1.9892,  ..., -1.9892, -1.9892, -1.9892],
         [-1.9892, -1.9892, -1.9892,  ..., -1.9892, -1.9892, -1.9892],
         [-1.9892, -1.9892, -1.9892,  ..., -1.9892, -1.9892, -1.9892]],

        [[-1.9802, -1.9802, -1.9802,  ..., -0.5307, -0.4824, -0.5307],
         [-1.9802, -1.9802, -1.9802,  ..., -0.7079, -0.7079, -0.9011],
         [-1.9802, -1.9802, -1.9802,  ..., -0.6918, -0.8850, -1.1105],
         ...,
         [-1.9802, -1.9802, -1.9802,  ..., -1.9802, -1.9802, -1.9802],
         [-1.9802, -1.9802, -1.9802,  ..., -1.9802, -1.9802, -1.9802],
         [-1.9802, -1.9802, -1.9802,  ..., -1.9802, -1.9802, -1.9802]],

        [[-1.7070, -1.7070, -1.7070,  ..., -0.9724, -0.9424, -0.9574],
         [-1.7070, -1.7070, -1.7070,  ..., -1

In [22]:
np.array(train_data[0][0]).shape

(32, 32, 3)

In [2]:
x = torch.tensor([[1, 2, 3, 4], [0, 2, 5, 0]])

In [3]:
y = torch.FloatTensor(2, 4).zero_()

In [7]:
for i in range(len(x)):
    for j in range(x.size(1)):
        if bool(x[i][j] == torch.min(x[i])):
            y[i][j] = 1
            break

In [8]:
y

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.]])

In [39]:
np.min(x.numpy(), 1)[0]

1

In [37]:
torch.min(x, 1)[0]

tensor([1, 0])

tensor([[1, 2, 3, 4],
        [0, 2, 5, 0]])